name: "Network"
version: "1.0"

channels:
  comunitychannel:
    orderers:
      - orderer0.hospital1.switch2logic.co.za
      - orderer0.hospital2.switch2logic.co.za
      - orderer0.hospital3.switch2logic.co.za      
    peers:
      peer0.hospital1.switch2logic.co.za:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer0.hospital2.switch2logic.co.za:
        endorsingPeer: true
        chaincodeQuery: false
        ledgerQuery: true
        eventSource: false

organizations:
  Hospital1:
    mspid: Hospital1MSP
    peers:
      - peer0.hospital1.switch2logic.co.za
    certificateAuthorities:
      - ca-hospital1
    adminPrivateKey:
      path: ../crypto-config/peerOrganizations/hospital1.switch2logic.co.za/users/Admin@hospital1.switch2logic.co.za/msp/keystore/886e1ce74760b8f991f02b47bbabaaf6ff019894c1c7316e45bf6c982bdf26c1_sk
    signedCert:
      path: ../crypto-config/peerOrganizations/hospital1.switch2logic.co.za/users/Admin@hospital1.switch2logic.co.za/msp/signcerts/Admin@hospital1.switch2logic.co.za-cert.pem

  Hospital2:
    mspid: Hospital2MSP
    peers:
      - peer0.hospital2.switch2logic.co.za
    certificateAuthorities:
      - ca-hospital2
    adminPrivateKey:
      path: ../crypto-config/peerOrganizations/hospital2.switch2logic.co.za/users/Admin@hospital2.switch2logic.co.za/msp/keystore/f2dabe474312d3297e693af0b1c8ff53216db9bcfe54c4d4922e1d00e6a83712_sk
    signedCert:
      path: ../crypto-config/peerOrganizations/hospital2.switch2logic.co.za/users/Admin@hospital2.switch2logic.co.za/msp/signcerts/Admin@hospital2.switch2logic.co.za-cert.pem

orderers:
  orderer0.hospital1.switch2logic.co.za:
    url: grpcs://orderer0.hospital1.switch2logic.co.za:7050
    grpcOptions:
      ssl-target-name-override: orderer0.hospital1.switch2logic.co.za
      grpc-max-send-message-length: 15
    tlsCACerts:
      path: ../crypto-config/ordererOrganizations/switch2logic.co.za/orderers/orderer0.hospital1.switch2logic.co.za/tlscacerts/msp/tlsca.switch2logic.co.za-cert.pem

  orderer0.hospital2.switch2logic.co.za:
    url: grpcs://orderer0.hospital2.switch2logic.co.za:7050
    grpcOptions:
      ssl-target-name-override: orderer0.hospital2.switch2logic.co.za
      grpc-max-send-message-length: 15
    tlsCACerts:
      path: ../crypto-config/ordererOrganizations/switch2logic.co.za/orderers/orderer0.hospital2.switch2logic.co.za/tlscacerts/msp/tlsca.switch2logic.co.za-cert.pem

  orderer0.hospital3.switch2logic.co.za:
    url: grpcs://orderer0.hospital3.switch2logic.co.za:7050
    grpcOptions:
      ssl-target-name-override: orderer0.hospital3.switch2logic.co.za
      grpc-max-send-message-length: 15
    tlsCACerts:
      path: ../crypto-config/ordererOrganizations/switch2logic.co.za/orderers/orderer0.hospital3.switch2logic.co.za/tlscacerts/msp/tlsca.switch2logic.co.za-cert.pem

peers:
  peer0.hospital1.switch2logic.co.za:
    url: grpcs://peer0.hospital1.switch2logic.co.za:7051
    eventUrl: grpcs://peer0.hospital1.switch2logic.co.za:7053
    grpcOptions:
      ssl-target-name-override: peer0.hospital1.switch2logic.co.za
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: ../crypto-config/peerOrganizations/hospital1.switch2logic.co.za/peers/peer0.hospital1.switch2logic.co.za/msp/tlscacerts/tlsca.hospital1.switch2logic.co.za-cert.pem

  peer0.hospital2.switch2logic.co.za:
    url: grpcs://peer2.swicth2logic.co.za:7051
    eventUrl: grpcs://peer2.swicth2logic.co.za:7053
    grpcOptions:
      ssl-target-name-override: peer0.hospital2.switch2logic.co.za
    tlsCACerts:
      path: ../crypto-config/peerOrganizations/hospital2.switch2logic.co.za/peers/peer0.hospital2.switch2logic.co.za/msp/tlscacerts/tlsa.hospital2.switch2logic.co.za-cert.pem

certificateAuthorities:
  ca-hospital1:
    url: https://ca.hospital1.switch2logic.co.za:7054
    httpOptions:
      verify: false
    tlsCACerts:
      path: ../crypto-config/peerOrganizations/hospital1.switch2logic.co.za/ca/ca.hospital1.switch2logic.co.za-cert.pem
    registrar:
      - enrollId: admin
        enrollSecret: adminpw
    caName: cahospital1

  ca-hospital2:
    url: https://ca.hospital2.switch2logic.co.za:8054
    httpOptions:
      verify: false
    tlsCACerts:
      path: ../crypto-config/peerOrganizations/hospital2.switch2logic.co.za/ca/hospital2.switch2logic.co.za-cert.pem
    registrar:
      - enrollId: admin
        enrollSecret: adminpw
    caName: cahospital2